import type { WordItem, GameLevel } from './types';

export const WORD_BANK: WordItem[] = [
  // --- TK (Kindergarten: 3 to 6 Letters) ---
  {
    id: 'tk_mata',
    word: 'MATA',
    clue: 'Alat untuk melihat indahnya dunia di sekitar kita.',
    explanation: 'Mata menangkap cahaya agar kita bisa melihat bentuk, warna, dan orang-orang tersayang.',
    category: 'Indra',
    level: 'TK',
    group: 'panca-indra',
    atlasTarget: 'eye',
  },
  {
    id: 'tk_kaki',
    word: 'KAKI',
    clue: 'Bagian tubuh bawah untuk berdiri, berjalan, dan melompat.',
    explanation: 'Kaki menopang berat seluruh tubuh dan membantu kita bergerak ke mana saja dengan lincah.',
    category: 'Gerak',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'femur',
  },
  {
    id: 'tk_jari',
    word: 'JARI',
    clue: 'Ujung tangan yang lentik untuk memegang pensil atau sendok.',
    explanation: 'Setiap tangan kita punya lima jari yang bekerja sama saat menulis, menggambar, dan bersalaman.',
    category: 'Gerak',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'hand',
  },
  {
    id: 'tk_gigi',
    word: 'GIGI',
    clue: 'Benda putih keras di dalam mulut untuk mengunyah makanan.',
    explanation: 'Gigi memotong dan menghaluskan makanan agar perut kita mudah mencernanya. Rajin sikat gigi ya!',
    category: 'Pencernaan',
    level: 'TK',
    group: 'mulut',
    atlasTarget: 'skull',
  },
  {
    id: 'tk_pipi',
    word: 'PIPI',
    clue: 'Bagian samping wajah yang mengembang saat kita tersenyum.',
    explanation: 'Pipi berada di samping hidung dan mulut, melindungi bagian dalam rongga mulut saat makan.',
    category: 'Wajah',
    level: 'TK',
    group: 'wajah',
    atlasTarget: 'skull',
  },
  {
    id: 'tk_kuku',
    word: 'KUKU',
    clue: 'Lapisan pelindung keras di ujung setiap jari tangan dan kaki.',
    explanation: 'Kuku melindungi ujung jari yang lembut dan banyak memiliki saraf perasa yang peka.',
    category: 'Pelindung',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'hand',
  },
  {
    id: 'tk_leher',
    word: 'LEHER',
    clue: 'Penghubung antara kepala dan badan agar bisa menoleh.',
    explanation: 'Di dalam leher ada tulang dan otot kuat yang menyangga kepala serta saluran untuk bernapas dan makan.',
    category: 'Rangka',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'vertebra',
  },
  {
    id: 'tk_lidah',
    word: 'LIDAH',
    clue: 'Alat di dalam mulut untuk mengecap rasa manis, asin, dan asam.',
    explanation: 'Lidah memiliki bintil perasa untuk mengenali rasa makanan serta membantu kita berbicara dengan jelas.',
    category: 'Indra',
    level: 'TK',
    group: 'panca-indra',
    atlasTarget: 'skull',
  },
  {
    id: 'tk_mulut',
    word: 'MULUT',
    clue: 'Pintu masuk makanan dan tempat kita berbicara serta tersenyum.',
    explanation: 'Mulut terdiri dari bibir, gigi, dan lidah yang bekerja sama untuk makan, minum, dan bersuara.',
    category: 'Pencernaan',
    level: 'TK',
    group: 'wajah',
    atlasTarget: 'skull',
  },
  {
    id: 'tk_hidung',
    word: 'HIDUNG',
    clue: 'Alat untuk mencium wangi bunga dan menghirup udara segar.',
    explanation: 'Hidung menyaring debu di udara sebelum masuk ke paru-paru sekaligus mencium bermacam-macam aroma.',
    category: 'Indra',
    level: 'TK',
    group: 'panca-indra',
    atlasTarget: 'nasal',
  },
  {
    id: 'tk_tangan',
    word: 'TANGAN',
    clue: 'Anggota tubuh atas untuk memegang, meraba, dan melambaikan salam.',
    explanation: 'Tangan memungkinkan manusia membuat karya seni, bermain alat musik, dan saling membantu.',
    category: 'Gerak',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'humerus',
  },
  {
    id: 'tk_kepala',
    word: 'KEPALA',
    clue: 'Bagian tubuh paling atas tempat mata, telinga, dan otak berada.',
    explanation: 'Kepala dilindungi oleh tulang tengkorak yang kokoh agar organ berharga seperti otak tetap aman.',
    category: 'Rangka',
    level: 'TK',
    group: 'anggota-badan',
    atlasTarget: 'skull',
  },
  {
    id: 'tk_rambut',
    word: 'RAMBUT',
    clue: 'Mahkota pelindung di atas kulit kepala.',
    explanation: 'Rambut menjaga kulit kepala dari teriknya sinar matahari dan hawa dingin angin malam.',
    category: 'Pelindung',
    level: 'TK',
    group: 'wajah',
    atlasTarget: 'skull',
  },

  // --- SD (Elementary: 4 to 7 Letters) ---
  {
    id: 'sd_otak',
    word: 'OTAK',
    clue: 'Pusat kendali seluruh pikiran, gerak, dan memori tubuh manusia.',
    explanation: 'Otak memproses miliaran sinyal setiap detik sehingga kita bisa berpikir, merasa, dan mengendalikan organ tubuh.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'saraf',
    atlasTarget: 'brain',
  },
  {
    id: 'sd_paru',
    word: 'PARU',
    clue: 'Organ pernapasan tempat pertukaran oksigen dan karbon dioksida.',
    explanation: 'Sepasang paru-paru mengembang saat menghirup oksigen segar dan mengempis saat menghembuskan udara kotor.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'pernapasan',
    atlasTarget: 'lung',
  },
  {
    id: 'sd_hati',
    word: 'HATI',
    clue: 'Kelenjar terbesar dalam tubuh yang menyaring racun dan memproduksi empedu.',
    explanation: 'Hati adalah laboratorium tubuh! Menetralkan racun berbahaya, menyimpan cadangan energi gula, dan membuat empedu.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'pencernaan',
    atlasTarget: 'liver',
  },
  {
    id: 'sd_usus',
    word: 'USUS',
    clue: 'Saluran panjang tempat penyerapan sari makanan dan air.',
    explanation: 'Usus halus menyerap gizi makanan untuk tubuh, sedangkan usus besar menyerap cairan dan membentuk sisa makanan.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'pencernaan',
    atlasTarget: 'small intestine',
  },
  {
    id: 'sd_darah',
    word: 'DARAH',
    clue: 'Cairan merah yang mengalirkan oksigen dan nutrisi ke seluruh sel.',
    explanation: 'Darah terdiri dari sel darah merah pembawa oksigen, sel darah putih penjaga imun, dan keping darah pembeku luka.',
    category: 'Sirkulasi',
    level: 'SD',
    group: 'peredaran-darah',
    atlasTarget: 'heart',
  },
  {
    id: 'sd_otot',
    word: 'OTOT',
    clue: 'Jaringan yang berkontraksi dan berelaksasi untuk menggerakkan tulang.',
    explanation: 'Lebih dari 600 otot di tubuh bekerja secara sinkron menarik tulang agar kita bisa bergerak dan berolahraga.',
    category: 'Gerak',
    level: 'SD',
    group: 'otot',
    atlasTarget: 'muscular',
  },
  {
    id: 'sd_sendi',
    word: 'SENDI',
    clue: 'Pertemuan antar dua tulang yang memungkinkan gerakan menekuk dan memutar.',
    explanation: 'Tanpa sendi tubuh kita akan kaku seperti kayu! Sendi engsel ada di siku dan lutut, sendi peluru di pundak.',
    category: 'Rangka',
    level: 'SD',
    group: 'tulang',
    atlasTarget: 'skeletal',
  },
  {
    id: 'sd_kulit',
    word: 'KULIT',
    clue: 'Organ terluar dan terluas yang melindungi organ dalam tubuh.',
    explanation: 'Kulit melindungi tubuh dari kuman dan sengatan sinar ultraviolet, serta mengeluarkan keringat pengatur suhu.',
    category: 'Pelindung',
    level: 'SD',
    group: 'indra',
    atlasTarget: 'integumentary',
  },
  {
    id: 'sd_ginjal',
    word: 'GINJAL',
    clue: 'Sepasang organ penyaring limbah darah yang membentuk air seni.',
    explanation: 'Ginjal bekerja non-stop membersihkan sekitar 200 liter darah setiap hari dan membuang zat sisa lewat urine.',
    category: 'Ekskresi',
    level: 'SD',
    group: 'perkemihan',
    atlasTarget: 'kidney',
  },
  {
    id: 'sd_tulang',
    word: 'TULANG',
    clue: 'Kerangka keras penopang bentuk tubuh dan pelindung organ vital.',
    explanation: 'Manusia dewasa memiliki 206 tulang yang kuat namun ringan. Tulang juga memproduksi sel-sel darah baru di sumsumnya.',
    category: 'Rangka',
    level: 'SD',
    group: 'tulang',
    atlasTarget: 'skeletal',
  },
  {
    id: 'sd_jantung',
    word: 'JANTUNG',
    clue: 'Organ berotot yang memompa darah ke seluruh tubuh tanpa henti.',
    explanation: 'Jantung berdenyut sekitar 100.000 kali per hari memompa darah kaya oksigen dari paru-paru ke seluruh bagian tubuh.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'peredaran-darah',
    atlasTarget: 'heart',
  },
  {
    id: 'sd_lambung',
    word: 'LAMBUNG',
    clue: 'Kantung pencerna yang mengolah makanan dengan asam lambung dan enzim.',
    explanation: 'Lambung mengaduk makanan seperti blender dan mencampurnya dengan asam kuat agar kuman mati dan protein tercerna.',
    category: 'Organ Utama',
    level: 'SD',
    group: 'pencernaan',
    atlasTarget: 'stomach',
  },
  {
    id: 'sd_telinga',
    word: 'TELINGA',
    clue: 'Alat pendengaran dan pengatur keseimbangan posisi tubuh kita.',
    explanation: 'Telinga menangkap gelombang suara di udara dan mengubahnya menjadi getaran yang dapat dipahami oleh otak.',
    category: 'Indra',
    level: 'SD',
    group: 'panca-indra',
    atlasTarget: 'sensory',
  },
  {
    id: 'sd_enzim',
    word: 'ENZIM',
    clue: 'Zat khusus pemecah molekul makanan agar cepat diserap sel tubuh.',
    explanation: 'Enzim bertindak sebagai biokatalisator yang mempercepat reaksi kimia pencernaan makanan menjadi energi.',
    category: 'Biokimia',
    level: 'SD',
    group: 'pencernaan',
    atlasTarget: 'pancreas',
  },
  {
    id: 'sd_liur',
    word: 'LIUR',
    clue: 'Cairan di rongga mulut pembawa enzim amilase pelumat makanan.',
    explanation: 'Air liur membasahi makanan agar mudah dikunyah dan ditelan, serta memulai proses pemecahan karbohidrat.',
    category: 'Biokimia',
    level: 'SD',
    group: 'mulut',
    atlasTarget: 'skull',
  },
];

export function getWordsForLevel(level: GameLevel): WordItem[] {
  return WORD_BANK.filter((item) => item.level === level);
}
